name: CI Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - name:Checkoutcode
      - uses: actions/checkout@v5


      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test
=======
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Test
        run: npm test --if-present
>>>>>>> 4c1775d (feat: add CI pipeline)
